# Generated by Django 3.0.2 on 2020-07-27 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_API', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='author',
            new_name='user',
        ),
    ]
